import rawSlides from '@/content/histologySlides.json'
import type { HistologySlide } from './types'

/**
 * The single source of histology slides. Records come verbatim from
 * `histologySlides.json` (generated by the extraction tool from the supplied
 * course slides). Adding new images = drop them in the source material and
 * re-run `python3 tools/extract_content.py`; no code change is needed here.
 */
export const SLIDES: HistologySlide[] = (rawSlides as HistologySlide[]).map((s) => ({
  ...s,
  labels: s.labels ?? [],
  text: s.text ?? [],
  annotations: s.annotations ?? [],
}))

export interface ChapterGroup {
  chapterId: string
  chapterTitle: string
  slides: HistologySlide[]
  /** Index into SLIDES of each slide, for O(1) navigation. */
  indices: number[]
}

/** Slides grouped by chapter, preserving source order. */
export function groupByChapter(slides: HistologySlide[] = SLIDES): ChapterGroup[] {
  const map = new Map<string, ChapterGroup>()
  slides.forEach((s, i) => {
    let g = map.get(s.chapterId)
    if (!g) {
      g = { chapterId: s.chapterId, chapterTitle: s.chapterTitle, slides: [], indices: [] }
      map.set(s.chapterId, g)
    }
    g.slides.push(s)
    g.indices.push(i)
  })
  return [...map.values()]
}

/** Case-insensitive match over title, caption, slide title, labels and text. */
export function slideMatches(s: HistologySlide, q: string): boolean {
  const needle = q.trim().toLowerCase()
  if (!needle) return true
  const hay = [s.title, s.caption, s.slideTitle, s.chapterTitle, ...(s.labels ?? []), ...(s.text ?? [])]
    .filter(Boolean)
    .join(' ')
    .toLowerCase()
  return hay.includes(needle)
}
