/**
 * Shared types for the histology microscopy experience.
 *
 * A `HistologySlide` mirrors one record of `src/content/histologySlides.json`,
 * which is generated by `tools/extract_content.py` from the supplied lecturee
 * slides. Every field is source-derived: `labels` and `text` are the verbatim
 * call-outs and sentences that sit on the same slide as the micrograph. Nothing
 * is invented — when a slide carries no real title/labels/text those arrays are
 * empty and the UI falls back to the chapter name.
 */
export interface SlideAnnotation {
  /** Normalized x over the image, 0–1 (left → right). Only from supplied data. */
  x: number
  /** Normalized y over the image, 0–1 (top → bottom). */
  y: number
  label: string
}

export interface HistologySlide {
  id: string
  src: string
  title: string
  caption?: string
  chapterId: string
  chapterTitle: string
  /** Source slide/page number within the chapter. */
  page?: number
  /** How many micrographs share this slide; >1 means the text is slide-level. */
  pageImageCount?: number
  /** Real slide heading, when the source provides one. */
  slideTitle?: string | null
  /** Short structure call-outs on the slide (e.g. "Endocardium"). */
  labels?: string[]
  /** Explanatory sentences from the slide. */
  text?: string[]
  /** Stain, only when genuinely mentioned in the source. */
  stain?: string | null
  /** Optional supplied coordinate annotations (never auto-generated). */
  annotations?: SlideAnnotation[]
}

/** A raw record as stored in histologySlides.json. */
export interface RawSlide extends HistologySlide {
  labels?: string[]
  text?: string[]
}
